### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by hinewu** [billpwchan/futu_algo#42]
**Describe the bug**
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Users\\admin\\Documents\\Python\\futu_algo-master\\data\\Stock_Pool\\ListOfSecurities.csv'

**Comment by billpwchan** [comment]
@hinewu Hi I think this is an error caused by missing ListOfSecurities.csv. This file was generated using an Excel directly download from HKEX, which contains all the currently listed securities in the Hong Kong Stock Market.
