### ISSUE TITLE
Can't install FutuOpenD via https://www.futunn.com/download/OpenAPI

### ISSUE THREAD

**Issue by spancer** [billpwchan/futu_algo#49]
Can't download futuOpenD via https://www.futunn.com/download/OpenAPI right now.

**Comment by billpwchan** [comment]
@spancer the URL looks fine to me, please kindly check again. 

![image](https://github.com/billpwchan/futu_algo/assets/25129943/c12f5e5d-b26d-42d2-b042-8ea4572bd9ce)

**Comment by JAfox1024** [comment]
you can download by this link ,https://cowtransfer.com/s/c6ae166e13fc47   Key: xzff70

**Comment by coreyzzp** [comment]
> you can download by this link ,https://cowtransfer.com/s/c6ae166e13fc47 Key: xzff70

any mac version?

**Comment by spancer** [comment]
> > you can download by this link ,https://cowtransfer.com/s/c6ae166e13fc47 Key: xzff70
> 
> any mac version?

thanks a ton.
